#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu May 28 02:47:58 KST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=BSL_v10.1.1.zip
