vectors:
  normal:
    firstPersonLeftRotation: {x: 0.0, y: 0.0, z: 0.0}
    firstPersonLeftTranslation: {x: 0.0, y: 0.0, z: 0.0}
    firstPersonRightScale: {x: 0.0, y: 0.0, z: 0.0}
    firstPersonRightTranslation: {x: 0.0, y: 0.0, z: 0.0}
    firstPersonRightRotation: {x: 0.0, y: 0.0, z: 0.0}
    firstPersonLeftScale: {x: 0.0, y: 0.0, z: 0.0}
  IRON_SWORD_RIGHT:
    firstPersonLeftRotation: {x: 0.0, y: 0.0, z: 0.0}
    firstPersonLeftTranslation: {x: 0.0, y: 0.0, z: 0.0}
    firstPersonRightScale: {x: -5.0, y: -5.0, z: -5.0}
    firstPersonRightTranslation: {x: 0.0, y: 0.0, z: 0.0}
    firstPersonRightRotation: {x: 0.0, y: 0.0, z: 0.0}
    firstPersonLeftScale: {x: 0.0, y: 0.0, z: 0.0}
connectedServers: ['182.216.39.123:20007']
clientId: 8a44764f-c55c-48ea-b706-786593a9c3b3
